### ISSUE TITLE
Implement login via key file functionality

### ISSUE THREAD

**Issue by agutsal** [agutsal/arweave-open-knowledge#1]
@janus please check among existing repositories, find out any typescript React one which has login via keyfile functionality and incorporate it into our source code. I think that Login button (and dropzone control, should reside somewhere at the top. Probably we need some toolbar for it). 

Lemme know if you have questions.

**Comment by janus** [comment]
@agutsal ,
Thanks assigning me that.. 
 I hope more would be coming

**Comment by agutsal** [comment]
Analyzing their SDK and trying to think out overall architecture. Need some time for that. In the meantime we'll work on preparation. Once login is done I'll think on jest/selenium tests, setup CI with code coverage and other stuff. That will save us lots of time in the future.

**Comment by janus** [comment]
Great ...

**Comment by janus** [comment]
Let's rub ideas together while analyzing their SDK and the archiecture

**Comment by agutsal** [comment]
@janus plz, update recent codebase. Minor changes, but anyway. Apply `.editorconfig` (guess you should have IDE plugin for it). Will work on CI now, continue tomorrow.

**Comment by janus** [comment]
https://github.com/agutsal/arweave-open-knowledge/pull/2
Check and review

**Comment by agutsal** [comment]
I'm experience this pretty strange error when running your branch (with merged master in it):
![image](https://user-images.githubusercontent.com/1643117/60804271-ce936800-a185-11e9-9771-6de0e21bf770.png)


Do you expect something similar?

**Comment by agutsal** [comment]
Fixed issue reported above. Plz, update `janus_knowledge` branch. Tests fails

**Comment by aahutsal** [comment]
[WIP] #5 contains requested functionality
